config/routes.rb
Enigmates::Application.routes.draw do
  get '/login', to: 'sessions#new'
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  get '/logout', to: 'sessions#destroy'
  
  root to: "puzzles#index"
  resources :puzzles, only: [:index] do
    resources :attempts, only: [:show, :create] do
      post "build_chart", as: "build_chart"
      resources :guesses, only: [:create]
      resources :messages, only: [:create]
    end
  end
  match 'invites/:attempt_id/', to: "invites#create"
end

app/models/puzzle.rb
 class Puzzle < ActiveRecord::Base
  attr_accessible :name, :topic, :format, :image_url, :content_noun, :hint_noun, :summary
  has_many :pieces
  has_many :attempts

  def to_s
    name
  end

  def contents
    (pieces.map(&:content) + pieces.map(&:alternatives)).compact
  end

  def total
    pieces.count
  end

  def pieces_in_pairs
    pieces.each_slice(2).to_a
  end
end 

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  before_filter :require_login

  def index
    @puzzles = Puzzle.all
  end
end

app/views/puzzles/index.html.erb
<div class="row">
  <h3>Featured Puzzles</h3>
  <% @puzzles.each do |puzzle| %>
    <div class="span4 puzzle-box">

      <h4><%= puzzle %></h4>

      <div class="flip"> 
        <div class="card"> 
          <div class="face front">
            <img src="assets/<%= puzzle.image_url %>" class="img-circle" />
          </div>
          <div class="face back">
            <div class='img-polaroid'>
              <%= puzzle.summary %>
            </div>
          </div> 
        </div> 
      </div> 

      <p>Play modes</p>

      <div class="btn-group">
        <%= link_to 'Co-Op', puzzle_attempts_path(puzzle, mode: "co-op"), method: :post, class: "btn btn-success" %>
        <%= link_to 'Versus', puzzle_attempts_path(puzzle, mode: "versus"), method: :post, class: "btn pull-right" %>
      </div>

    </div>
  <% end %>
</div>



<script type="text/javascript">
//  $('.flip').on('mouseover', function(){
//     $(this).find('.card').addClass('flipped').mouseleave(function(){
//         $(this).removeClass('flipped');
//     });
//     return false;
// });
</script>